services:
  microservice_admin_database:
    container_name: microservice_admin_database
    image: mariadb:10.7.4
    ports:
      - "3364:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - admin_network
  microservice_admin_php:
    container_name: microservice_admin_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    ports:
      - "8034:8000"
      - "9034:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: php artisan serve --host=0.0.0.0
    depends_on:
      - microservice_admin_database
    networks:
      - admin_network
networks:
  admin_network: