services:
  microservice_email_php:
    container_name: microservice_email_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    ports:
      - "8030:80"
      - "9030:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: php artisan serve --host=0.0.0.0 --port=8030